//! Pure DM05 schedule, prefix-layout and positional mathematics.

use apxinf_core::{Error, Result, Tensor};
use half::bf16;

use super::Dm05Config;
#[cfg(test)]
use super::Dm05RopeConfig;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AttentionSegment {
    pub query_start: usize,
    pub query_end: usize,
    /// Keys are the contiguous prefix `[0, key_end)`.
    pub key_end: usize,
    /// Causal attention uses bottom-right alignment when Q is a suffix of K.
    pub causal: bool,
}

/// Decompose Gemma3's two image-block overlay into causal text and unmasked
/// image-query intervals. Concatenating the five outputs restores token order.
pub fn prefix_attention_segments(
    config: &Dm05Config,
    token_ids: &[u32],
) -> Result<Vec<AttentionSegment>> {
    let [(first_start, first_end), (second_start, second_end)] =
        config.validate_prefix_tokens(token_ids)?;
    let boundaries = [
        (0, first_start, first_start, true),
        (first_start, first_end, first_end, false),
        (first_end, second_start, second_start, true),
        (second_start, second_end, second_end, false),
        (second_end, token_ids.len(), token_ids.len(), true),
    ];
    Ok(boundaries
        .into_iter()
        .filter(|(start, end, _, _)| start < end)
        .map(
            |(query_start, query_end, key_end, causal)| AttentionSegment {
                query_start,
                query_end,
                key_end,
                causal,
            },
        )
        .collect())
}

/// Exact BF16 values produced by Python's `time_val += -0.1` schedule before
/// each of the ten OpenDM Euler steps.
pub fn time_values() -> [bf16; 10] {
    [
        1.0,
        0.898_437_5,
        0.800_781_25,
        0.699_218_75,
        0.601_562_5,
        0.5,
        0.400_390_625,
        0.300_781_25,
        0.200_195_312_5,
        0.100_097_656_25,
    ]
    .map(bf16::from_f32)
}

/// Host formula used only to test the model-owned RoPE parameters. Shipping
/// tables are generated by the CUDA safe operator so transcendental rounding
/// matches the reference device path.
#[cfg(test)]
fn rope_tables(
    positions: &[u32],
    head_dim: usize,
    rope: Dm05RopeConfig,
) -> Result<(Tensor, Tensor)> {
    if positions.is_empty()
        || head_dim == 0
        || head_dim % 2 != 0
        || !rope.theta.is_finite()
        || rope.theta <= 0.0
        || !rope.linear_factor.is_finite()
        || rope.linear_factor <= 0.0
    {
        return Err(Error::Other(format!(
            "invalid DM05 RoPE table contract: positions={}, head_dim={head_dim}, rope={rope:?}",
            positions.len()
        )));
    }
    let half = head_dim / 2;
    let mut cosine = Vec::with_capacity(positions.len() * head_dim);
    let mut sine = Vec::with_capacity(positions.len() * head_dim);
    for &position in positions {
        let mut row_cos = Vec::with_capacity(half);
        let mut row_sin = Vec::with_capacity(half);
        for pair in 0..half {
            let exponent = 2.0 * pair as f32 / head_dim as f32;
            let inverse_frequency = 1.0 / rope.theta.powf(exponent) / rope.linear_factor;
            let angle = position as f32 * inverse_frequency;
            row_cos.push(bf16::from_f32(angle.cos()));
            row_sin.push(bf16::from_f32(angle.sin()));
        }
        cosine.extend_from_slice(&row_cos);
        cosine.extend_from_slice(&row_cos);
        sine.extend_from_slice(&row_sin);
        sine.extend_from_slice(&row_sin);
    }
    let shape = vec![positions.len(), head_dim];
    Ok((
        Tensor::from_bf16(shape.clone(), &cosine)?,
        Tensor::from_bf16(shape, &sine)?,
    ))
}

/// Dense block-diagonal average-pool matrix used by the correctness-first
/// projector path. `pool @ vision_hidden` is exactly the fixed 2x2/stride-2
/// spatial average for each view; a dedicated kernel is only warranted after
/// profiling.
pub fn projector_pool_matrix(config: &Dm05Config) -> Result<Tensor> {
    let input_side = config.patches_per_side();
    let output_side = config.pooled_side();
    let kernel = config.pool_kernel();
    if kernel != 2 || input_side != output_side * kernel {
        return Err(Error::Other(
            "DM05 projector pool matrix requires exact 2x2 pooling".into(),
        ));
    }
    let input_per_view = input_side * input_side;
    let output_per_view = output_side * output_side;
    let input_rows = config.num_views * input_per_view;
    let output_rows = config.num_views * output_per_view;
    let mut matrix = vec![bf16::ZERO; output_rows * input_rows];
    let quarter = bf16::from_f32(0.25);
    for view in 0..config.num_views {
        for output_y in 0..output_side {
            for output_x in 0..output_side {
                let output = view * output_per_view + output_y * output_side + output_x;
                for dy in 0..kernel {
                    for dx in 0..kernel {
                        let input_y = output_y * kernel + dy;
                        let input_x = output_x * kernel + dx;
                        let input = view * input_per_view + input_y * input_side + input_x;
                        matrix[output * input_rows + input] = quarter;
                    }
                }
            }
        }
    }
    Tensor::from_bf16(vec![output_rows, input_rows], &matrix)
}

pub fn action_mask(config: &Dm05Config) -> Result<Tensor> {
    if config.deploy_action_dim > config.action_dim {
        return Err(Error::Other(
            "DM05 deploy action width exceeds internal action width".into(),
        ));
    }
    let mut values = vec![bf16::ZERO; config.action_horizon * config.action_dim];
    for row in 0..config.action_horizon {
        values[row * config.action_dim..row * config.action_dim + config.deploy_action_dim]
            .fill(bf16::ONE);
    }
    Tensor::from_bf16(vec![config.action_horizon, config.action_dim], &values)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dm05::config::tests_support::exact_config;

    #[test]
    fn qualification_layout_becomes_five_exact_attention_segments() {
        let config = exact_config();
        let mut ids = vec![2; 564];
        ids[37..293].fill(config.image_token_id);
        ids[301..557].fill(config.image_token_id);
        assert_eq!(
            prefix_attention_segments(&config, &ids).unwrap(),
            vec![
                AttentionSegment {
                    query_start: 0,
                    query_end: 37,
                    key_end: 37,
                    causal: true
                },
                AttentionSegment {
                    query_start: 37,
                    query_end: 293,
                    key_end: 293,
                    causal: false
                },
                AttentionSegment {
                    query_start: 293,
                    query_end: 301,
                    key_end: 301,
                    causal: true
                },
                AttentionSegment {
                    query_start: 301,
                    query_end: 557,
                    key_end: 557,
                    causal: false
                },
                AttentionSegment {
                    query_start: 557,
                    query_end: 564,
                    key_end: 564,
                    causal: true
                },
            ]
        );
    }

    #[test]
    fn time_schedule_matches_reference_bf16_values() {
        let values = time_values().map(bf16::to_f32);
        assert_eq!(
            values,
            [
                1.0,
                0.8984375,
                0.80078125,
                0.69921875,
                0.6015625,
                0.5,
                0.400390625,
                0.30078125,
                0.2001953125,
                0.10009765625
            ]
        );
    }

    #[test]
    fn full_rope_linear_factor_changes_angles() {
        let config = exact_config();
        let positions = [564, 565];
        let (sliding_cos, _) = rope_tables(&positions, 256, config.language.sliding_rope).unwrap();
        let (full_cos, _) = rope_tables(&positions, 256, config.language.full_rope).unwrap();
        assert_ne!(sliding_cos.as_bf16().unwrap(), full_cos.as_bf16().unwrap());
        assert_eq!(full_cos.shape().dims(), [2, 256]);
    }

    #[test]
    fn pool_matrix_has_four_quarter_weights_per_output_and_is_view_local() {
        let config = exact_config();
        let matrix = projector_pool_matrix(&config).unwrap();
        assert_eq!(matrix.shape().dims(), [512, 2048]);
        let values = matrix.as_bf16().unwrap();
        for row in [0usize, 255, 256, 511] {
            let row = &values[row * 2048..(row + 1) * 2048];
            assert_eq!(
                row.iter()
                    .filter(|value| **value == bf16::from_f32(0.25))
                    .count(),
                4
            );
        }
        assert!(values[..2048]
            .iter()
            .skip(1024)
            .all(|value| *value == bf16::ZERO));
        assert!(values[256 * 2048..257 * 2048]
            .iter()
            .take(1024)
            .all(|value| *value == bf16::ZERO));
    }

    #[test]
    fn action_mask_preserves_only_libero_dimensions() {
        let config = exact_config().with_action_horizon(10).unwrap();
        let mask = action_mask(&config).unwrap();
        assert_eq!(mask.shape().dims(), [10, 32]);
        for row in mask.as_bf16().unwrap().chunks_exact(32) {
            assert!(row[..7].iter().all(|value| *value == bf16::ONE));
            assert!(row[7..].iter().all(|value| *value == bf16::ZERO));
        }
    }
}
